### ISSUE TITLE
Not Seeing Dropdown For States

### ISSUE THREAD

**Issue by trevorsmithbanjo** [dcastelline/Project-1-Rescue-Spot#21]
I'm not sure if anyone else is having this issue. I just deleted my branch and pulled the main and started a new branch so I should be up to date without conflicts. If no one else is having this problem we can close this issue and I'll try and figure out what is going on with my version.

-Trevor

**Comment by dcastelline** [comment]
Dropdown had to be initialized, I added the initialization to petfinder.js.
